" Autoamtically reload vimrc when it's saved
augroup ReloadVimrc
    au!
    au BufWritePost .vimrc so ~/.vimrc
    au BufWritePost ~/repos/dotfilese/vimrc so ~/.vimrc
augroup end

" Line numbers and tabs
set number
set relativenumber
set tabstop=4
set softtabstop=0
set expandtab
set shiftwidth=4
set smarttab
set autoindent
set smartindent
set noswapfile
set scrolloff=8
syntax on

" Folding
set foldmethod=indent
set nofoldenable
set foldnestmax=10
set foldlevel=1

" Split window opening
set splitbelow
set splitright

" Random remaps
nnoremap <space> i<space><right><esc>
nmap <CR> o<Esc>k
inoremap jj <Esc>


let mapleader="."
nnoremap <leader>h :noh<CR>

" Move singe line  or multiple lines up or down
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==
inoremap <C-j> <Esc>:m .+1<CR>==gi
inoremap <C-k> <Esc>:m .-2<CR>==gi
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv

" Move cursor to middle of screen when moving through search results
nnoremap n nzz
nnoremap N Nzz

" Easier window navigation
nnoremap <up> <C-w>k
nnoremap <down> <C-w>j
nnoremap <left> <C-w>h
nnoremap <right> <C-w>l

" Autocompletion
set wildmenu
set wildmode=list:longest,full

" Replace preview
if has("nvim")
    set inccommand=nosplit
endif


" Plug plugin manager
" https://github.com/junegunn/vim-plug
" For NeoVim run:
" sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
"
" After installation run :PlugInstall

call plug#begin('~/.vim/plugged')

" Colour schemes
Plug 'sjl/badwolf'
" Plug 'nightsense/carbonized'
Plug 'morhetz/gruvbox'
Plug 'mhartington/oceanic-next'

" tcomment_vim line commenter
Plug 'tomtom/tcomment_vim'

" Pydocstring
Plug 'heavenshell/vim-pydocstring', { 'do': 'make install', 'for': 'python' }

" ALE(Asynchronous Lint Engine)
Plug 'dense-analysis/ale'

" UndoTree
Plug 'mbbill/undotree'

" NERDTree file browser
Plug 'preservim/nerdtree'

" Easymotion (not really using this)
Plug 'easymotion/vim-easymotion'

" Airline git branch indicator
Plug 'vim-airline/vim-airline'

" Vim fugitive git merge tool
Plug 'tpope/vim-fugitive'

" Lightline status bar colouring
Plug 'itchyny/lightline.vim'

if has("nvim")
    Plug 'nvim-lua/popup.nvim'
    Plug 'nvim-lua/plenary.nvim'

    " Telescope
    Plug 'nvim-telescope/telescope.nvim'

    " Harpoon file marker
    Plug 'ThePrimeagen/harpoon'
endif

call plug#end()

" Colourscheme settings
syntax enable
if has("termguicolors")
    set termguicolors
endif
colorscheme OceanicNext

" Python docstring style
let g:pydocstring_formatter = 'google'
let g:pydocstring_doq_path ='~/.local/bin/doq'
command Docs Pydocstring


" Toggle undoTree
nnoremap <F5> :UndotreeToggle<CR>

" ALE Fixers and Linters
let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'python': ['autopep8', 'black'],
\}
let g:ale_linters = {
\   'python': ['flake8'],
\}
let g:ale_fix_on_save = 1
let g:ale_lint_delay = 50
let g:ale_python_pylint_options = "--generate-members"
let g:ale_python_flake8_options = "--max-line-length=88 --ignore F401,E203,W503"
" ALE Movement keys
nmap <silent> <F2> <Plug>(ale_previous_wrap)
nmap <silent> <F3> <Plug>(ale_next_wrap)
let g:python3_host_prog = "/usr/bin/python3"


" Telescope maps
nnoremap <leader>ff <cmd>Telescope find_files<cr>
nnoremap <leader>fg <cmd>Telescope live_grep<cr>
nnoremap <leader>fb <cmd>Telescope buffers<cr>
nnoremap <leader>fh <cmd>Telescope help_tags<cr>

" NerdTree maps
nnoremap <F4> :NERDTreeToggle<CR>
" Close NERDTree if it is the last window
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif

" Lightline color settings
let g:lightline ={
    \ 'colorscheme': 'wombat',
    \ }

" Harpoon maps
lua require("telescope").load_extension('harpoon')
nnoremap <C-e> <cmd>Telescope harpoon marks<CR>
lua vim.api.nvim_set_keymap('n',
\   '<leader>a',
\   "<cmd>lua require('harpoon.mark').add_file()<CR>",
\   {noremap = true})
lua vim.api.nvim_set_keymap('n',
\   '<F12>',
\   "<cmd>lua require('harpoon.ui').toggle_quick_menu()<CR>",
\   {noremap = true})
lua vim.api.nvim_set_keymap('n',
\   '<F1>',
\   "<cmd>lua require('harpoon.ui').nav_file(1)<CR>",
\   {noremap = true})
lua vim.api.nvim_set_keymap('n',
\   '<F2>',
\   "<cmd>lua require('harpoon.ui').nav_file(2)<CR>",
\   {noremap = true})
lua vim.api.nvim_set_keymap('n',
\   '<F3>',
\   "<cmd>lua require('harpoon.ui').nav_file(3)<CR>",
\   {noremap = true})
lua vim.api.nvim_set_keymap('n',
\   '<F4>',
\   "<cmd>lua require('harpoon.ui').nav_file(4)<CR>",
\   {noremap = true})
